# Copyright 2017-2020 GRAIL, Inc.
# Copyright 2020 NVIDIA, Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "compdb_tests")

new_local_repository(
    name = "compdb",
    build_file_content = "",
    path = "..",
)

load("@compdb//:config.bzl", "config_clang_compdb")

config_clang_compdb(
    workspace_name = "compdb_tests",
    filter_flags = [
        "-fno-canonical-system-headers",
    ],
    extra_configs = dict(
        clang_tidy_script_postfix = "_ctidy",
    ),
    extra_shell_configs = dict(
        # Complicated expression to demostrate shell syntax support.
        clang_tidy_exec = "eval echo $(which clang-tidy)",
    ),
)
